services:
  app:
    image: palma-taboola:latest
    build:
      context: .
    container_name: palma-taboola
    volumes:
      - ./creds/${CREDS_FILENAME}.json:/tmp/${CREDS_FILENAME}.json
      - ./data:/app/data
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/${CREDS_FILENAME}.json
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}

    ports:
      - '8080:8080'
    user: '0'
